## Import package

In [19]:
import numpy as np
import pandas as pd

## Column selection, addition, deletion

You can threat <u>`DataFrame`</u> semantically like a dict of like-indexed <u>`Series`</u> object. Getting, setting, and deleting columns works with the same syntax as the analogous dict operations:

In [20]:
df = {
    "one": pd.Series([1, 2, 3], index=["a", "b", "c"]),
    "two": pd.Series([1, 2, 3, 4], index=["a", "b", "c", "d"]),
}

In [21]:
df["one"]

a    1
b    2
c    3
dtype: int64

In [22]:
df["three"] = df["one"] * df["two"]

In [37]:
pd.DataFrame(df)

   one  foo  one_trunc
a    1  bar        1.0
b    2  bar        2.0
c    3  bar        NaN

Columns can be deleted or popped like with a dict:

In [24]:
del df["two"]

In [25]:
three = df.pop("three")

In [39]:
pd.DataFrame(df)

   one  foo  one_trunc
a    1  bar        1.0
b    2  bar        2.0
c    3  bar        NaN

In [40]:
df["foo"] = "bar"

In [41]:
pd.DataFrame(df)

   one  foo  one_trunc
a    1  bar        1.0
b    2  bar        2.0
c    3  bar        NaN

When inserting a <u>`Series`</u> that does not to have the same index as the <u>`DataFrame`</u>, it will be conformed to the DataFrame's index:

In [29]:
df["one_trunc"] = df["one"][:2]

In [43]:
pd.DataFrame(df)

   one  foo  one_trunc
a    1  bar        1.0
b    2  bar        2.0
c    3  bar        NaN

you can insert raw ndarrays but their length must match the length of the DataFrame's index.

By default, columns get inserted at the end. <u>`DataFrame.insert()`</u>inserts at a particular location in the columns:

In [48]:
df.insert(1, "bar", df["one"])

AttributeError: 'dict' object has no attribute 'insert'

In [45]:
pd.DataFrame(df)

   one  foo  one_trunc
a    1  bar        1.0
b    2  bar        2.0
c    3  bar        NaN